version: "3.8"

services:
  grafana:
    image: grafana/grafana:12.3.1
    ports:
      - 3000:3000
    volumes:
      - ./backend/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./backend/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    depends_on:
      - loki
      - tempo
      - mimir

  loki:
    image: grafana/loki:latest
    user: root
    ports:
      - "3100:3100"
    volumes:
      - ./backend/loki/loki.yaml:/etc/loki/loki.yaml
      - loki_data:/tmp/loki # Volume para persistência
    
  

  tempo:
    image: grafana/tempo:latest
    ports:
    - "3200:3200"
    volumes:
    - ./backend/tempo/tempo.yaml:/etc/tempo/tempo.yaml
    - tempo_data:/var/tempo
    command: -config.file=/etc/tempo/tempo.yaml

  mimir:
    image: grafana/mimir:latest
    ports:
      - "9009:9009"
    volumes:
      - ./backend/mimir/mimir.yaml:/etc/mimir/mimir.yaml
      - mimir_data:/data # Volume para persistência
    command: -config.file=/etc/mimir/mimir.yaml

  dice-api:
    build: ./app
    container_name: dice-api
    ports:
      - "5000:5000"
    environment:
      OTEL_SERVICE_NAME: dice-api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317 
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc 
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
      PYTHONUNBUFFERED: "1"
    depends_on:
      - otel-collector


  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.100.0 
    container_name: otel-collector
    volumes:
      - ./app/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "1888:1888"   # pprof
      - "8888:8888"   # métricas internas
      - "8889:8889"   # métricas exporter
      - "13133:13133" # health_check
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
   
  node-exporter:
    image: prom/node-exporter:v1.10.2
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    restart: unless-stopped

# ADICIONE ISSO NO FINAL DO ARQUIVO:
volumes:
  mimir_data:
  loki_data:
  tempo_data:
  grafana_data:
