apiVersion: 1

datasources:
  - name: Mimir
    uid: mimir
    type: prometheus
    url: http://mimir:9009/prometheus
    jsonData:
      httpMethod: POST
      prometheusType: Mimir

  - name: Loki
    uid: loki
    type: loki
    url: http://loki:3100

  - name: Tempo
    uid: tempo
    type: tempo
    url: http://tempo:3200
    jsonData:
      lokiSearch:
        datasourceUid: 'loki'
      serviceMap:
        datasourceUid: 'mimir'
      nodeGraph:
        enabled: true
      tracesToMetrics:
        datasourceUid: 'mimir'
        tags: [{ key: 'service.name', value: 'service_name' }]